use std::io::{Read, Write};
use std::path::PathBuf;

use portable_pty::{native_pty_system, ChildKiller, CommandBuilder, MasterPty, PtySize};
use serde::Serialize;
use tauri::{AppHandle, Emitter, Manager, State};
use uuid::Uuid;

use crate::error::{AppError, AppResult};
use crate::state::AppState;

pub struct PtySession {
    pub writer: Box<dyn Write + Send>,
    pub master: Box<dyn MasterPty + Send>,
    pub killer: Box<dyn ChildKiller + Send + Sync>,
    pub cwd: PathBuf,
    pub title: String,
}

#[derive(Serialize, Clone)]
pub struct SessionMeta {
    pub id: String,
    pub cwd: String,
    pub title: String,
}

#[derive(Serialize, Clone)]
struct ExitPayload {
    id: String,
    code: u32,
}

fn default_shell() -> String {
    std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into())
}

/// `id` is generated by the frontend (crypto.randomUUID) so it can attach
/// its `pty://data/{id}` listener BEFORE spawning — otherwise the first
/// prompt bytes can be emitted before anyone is listening.
#[tauri::command]
pub fn pty_spawn(
    app: AppHandle,
    state: State<'_, AppState>,
    id: Option<String>,
    cwd: Option<String>,
    cols: u16,
    rows: u16,
) -> AppResult<String> {
    let id = id.unwrap_or_else(|| Uuid::new_v4().to_string());
    if state.sessions.lock().contains_key(&id) {
        return Err(AppError::Pty(format!("session {id} already exists")));
    }
    let shell = default_shell();
    let cwd = cwd
        .map(PathBuf::from)
        .or_else(dirs::home_dir)
        .unwrap_or_else(|| PathBuf::from("/"));

    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| AppError::Pty(e.to_string()))?;

    let mut cmd = CommandBuilder::new(&shell);
    cmd.arg("-l"); // login shell so the user's PATH/rc files load
    cmd.cwd(&cwd);
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    // GUI apps don't inherit a locale on macOS. Without a UTF-8 LANG,
    // zsh falls back to the C locale and counts each BYTE of multibyte
    // glyphs as one cell — prompt frameworks (oh-my-posh, p10k) then
    // misplace the cursor and right-aligned segments.
    if std::env::var("LANG").is_err() {
        cmd.env("LANG", "en_US.UTF-8");
    }
    cmd.env("TERM_PROGRAM", "mainbound");

    let child = pair
        .slave
        .spawn_command(cmd)
        .map_err(|e| AppError::Pty(e.to_string()))?;
    // Drop the slave: the child owns its end now; keeping it open would
    // prevent EOF on the reader when the child exits.
    drop(pair.slave);

    let killer = child.clone_killer();
    let writer = pair
        .master
        .take_writer()
        .map_err(|e| AppError::Pty(e.to_string()))?;
    let reader = pair
        .master
        .try_clone_reader()
        .map_err(|e| AppError::Pty(e.to_string()))?;

    spawn_reader_thread(app.clone(), id.clone(), reader);
    spawn_wait_thread(app, id.clone(), child);

    let title = shell.rsplit('/').next().unwrap_or(&shell).to_string();
    state.sessions.lock().insert(
        id.clone(),
        PtySession {
            writer,
            master: pair.master,
            killer,
            cwd,
            title,
        },
    );

    Ok(id)
}

/// Streams PTY output to the webview as `pty://data/{id}` events.
/// Chunks are emitted as UTF-8 strings; bytes that straddle a chunk
/// boundary are buffered until the sequence completes.
fn spawn_reader_thread(app: AppHandle, id: String, mut reader: Box<dyn Read + Send>) {
    std::thread::spawn(move || {
        let event = format!("pty://data/{id}");
        let mut buf = [0u8; 8192];
        let mut pending: Vec<u8> = Vec::new();

        loop {
            match reader.read(&mut buf) {
                Ok(0) | Err(_) => break, // EOF: child exited
                Ok(n) => {
                    pending.extend_from_slice(&buf[..n]);
                    let valid_len = match std::str::from_utf8(&pending) {
                        Ok(_) => pending.len(),
                        Err(e) => e.valid_up_to(),
                    };
                    if valid_len > 0 {
                        let chunk =
                            unsafe { std::str::from_utf8_unchecked(&pending[..valid_len]) };
                        let _ = app.emit(&event, chunk.to_string());
                        pending.drain(..valid_len);
                    }
                    // Defensive: if garbage accumulates (non-UTF-8 binary
                    // output), don't grow the buffer forever.
                    if pending.len() > 4 {
                        let _ = app.emit(&event, String::from_utf8_lossy(&pending).into_owned());
                        pending.clear();
                    }
                }
            }
        }
    });
}

/// Waits for the child to exit, then notifies the webview and cleans up.
fn spawn_wait_thread(
    app: AppHandle,
    id: String,
    mut child: Box<dyn portable_pty::Child + Send + Sync>,
) {
    std::thread::spawn(move || {
        let code = child.wait().map(|s| s.exit_code()).unwrap_or(1);
        if let Some(state) = app.try_state::<AppState>() {
            state.sessions.lock().remove(&id);
        }
        let _ = app.emit(
            &format!("pty://exit/{id}"),
            ExitPayload { id: id.clone(), code },
        );
    });
}

#[tauri::command]
pub fn pty_write(state: State<'_, AppState>, id: String, data: String) -> AppResult<()> {
    let mut sessions = state.sessions.lock();
    let session = sessions
        .get_mut(&id)
        .ok_or_else(|| AppError::SessionNotFound(id.clone()))?;
    session.writer.write_all(data.as_bytes())?;
    session.writer.flush()?;
    Ok(())
}

#[tauri::command]
pub fn pty_resize(state: State<'_, AppState>, id: String, cols: u16, rows: u16) -> AppResult<()> {
    let sessions = state.sessions.lock();
    let session = sessions
        .get(&id)
        .ok_or_else(|| AppError::SessionNotFound(id.clone()))?;
    session
        .master
        .resize(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })
        .map_err(|e| AppError::Pty(e.to_string()))
}

#[tauri::command]
pub fn pty_kill(state: State<'_, AppState>, id: String) -> AppResult<()> {
    let mut sessions = state.sessions.lock();
    if let Some(mut session) = sessions.remove(&id) {
        let _ = session.killer.kill();
    }
    Ok(())
}

#[tauri::command]
pub fn pty_list(state: State<'_, AppState>) -> Vec<SessionMeta> {
    state
        .sessions
        .lock()
        .iter()
        .map(|(id, s)| SessionMeta {
            id: id.clone(),
            cwd: s.cwd.to_string_lossy().into_owned(),
            title: s.title.clone(),
        })
        .collect()
}
